package com.haoyu.family_blog.Model;

import java.io.Serializable;
import java.util.Date;

public class BlogVisitLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_visit_log.id
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_visit_log.userId
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_visit_log.blogId
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private Long blogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_visit_log.visitTime
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private Date visittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_visit_log.hide
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private Integer hide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_visit_log.id
     *
     * @return the value of blog_visit_log.id
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_visit_log.id
     *
     * @param id the value for blog_visit_log.id
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_visit_log.userId
     *
     * @return the value of blog_visit_log.userId
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_visit_log.userId
     *
     * @param userid the value for blog_visit_log.userId
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_visit_log.blogId
     *
     * @return the value of blog_visit_log.blogId
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public Long getBlogid() {
        return blogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_visit_log.blogId
     *
     * @param blogid the value for blog_visit_log.blogId
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setBlogid(Long blogid) {
        this.blogid = blogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_visit_log.visitTime
     *
     * @return the value of blog_visit_log.visitTime
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public Date getVisittime() {
        return visittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_visit_log.visitTime
     *
     * @param visittime the value for blog_visit_log.visitTime
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setVisittime(Date visittime) {
        this.visittime = visittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_visit_log.hide
     *
     * @return the value of blog_visit_log.hide
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public Integer getHide() {
        return hide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_visit_log.hide
     *
     * @param hide the value for blog_visit_log.hide
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setHide(Integer hide) {
        this.hide = hide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userid=").append(userid);
        sb.append(", blogid=").append(blogid);
        sb.append(", visittime=").append(visittime);
        sb.append(", hide=").append(hide);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}