package com.haoyu.family_blog.Model;

import java.io.Serializable;
import java.util.Date;

public class Blog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.created_by
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private Long createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.time
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.hearts
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private Integer hearts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.title
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.created_by
     *
     * @return the value of blog.created_by
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.created_by
     *
     * @param createdBy the value for blog.created_by
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.time
     *
     * @return the value of blog.time
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.time
     *
     * @param time the value for blog.time
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.hearts
     *
     * @return the value of blog.hearts
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public Integer getHearts() {
        return hearts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.hearts
     *
     * @param hearts the value for blog.hearts
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setHearts(Integer hearts) {
        this.hearts = hearts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.title
     *
     * @return the value of blog.title
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.title
     *
     * @param title the value for blog.title
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content
     *
     * @return the value of blog.content
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content
     *
     * @param content the value for blog.content
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", time=").append(time);
        sb.append(", hearts=").append(hearts);
        sb.append(", title=").append(title);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}