package com.haoyu.family_blog.Model;

import java.io.Serializable;
import java.util.Date;

public class UserLoginLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.id
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.user_id
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.time
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.ip
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.address
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_log.user_agent
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private String userAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_login_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.id
     *
     * @return the value of user_login_log.id
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.id
     *
     * @param id the value for user_login_log.id
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.user_id
     *
     * @return the value of user_login_log.user_id
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.user_id
     *
     * @param userId the value for user_login_log.user_id
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.time
     *
     * @return the value of user_login_log.time
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.time
     *
     * @param time the value for user_login_log.time
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.ip
     *
     * @return the value of user_login_log.ip
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.ip
     *
     * @param ip the value for user_login_log.ip
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.address
     *
     * @return the value of user_login_log.address
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.address
     *
     * @param address the value for user_login_log.address
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_log.user_agent
     *
     * @return the value of user_login_log.user_agent
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_log.user_agent
     *
     * @param userAgent the value for user_login_log.user_agent
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", time=").append(time);
        sb.append(", ip=").append(ip);
        sb.append(", address=").append(address);
        sb.append(", userAgent=").append(userAgent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}