package com.haoyu.family_blog.Model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.id
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.username
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.password
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.avatar
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.email
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.nick_name
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.note
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.create_time
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.login_time
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.status
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.role
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table User
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.id
     *
     * @return the value of User.id
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.id
     *
     * @param id the value for User.id
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.username
     *
     * @return the value of User.username
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.username
     *
     * @param username the value for User.username
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.password
     *
     * @return the value of User.password
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.password
     *
     * @param password the value for User.password
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.avatar
     *
     * @return the value of User.avatar
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.avatar
     *
     * @param avatar the value for User.avatar
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.email
     *
     * @return the value of User.email
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.email
     *
     * @param email the value for User.email
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.nick_name
     *
     * @return the value of User.nick_name
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.nick_name
     *
     * @param nickName the value for User.nick_name
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.note
     *
     * @return the value of User.note
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.note
     *
     * @param note the value for User.note
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.create_time
     *
     * @return the value of User.create_time
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.create_time
     *
     * @param createTime the value for User.create_time
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.login_time
     *
     * @return the value of User.login_time
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.login_time
     *
     * @param loginTime the value for User.login_time
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.status
     *
     * @return the value of User.status
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.status
     *
     * @param status the value for User.status
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.role
     *
     * @return the value of User.role
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.role
     *
     * @param role the value for User.role
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", avatar=").append(avatar);
        sb.append(", email=").append(email);
        sb.append(", nickName=").append(nickName);
        sb.append(", note=").append(note);
        sb.append(", createTime=").append(createTime);
        sb.append(", loginTime=").append(loginTime);
        sb.append(", status=").append(status);
        sb.append(", role=").append(role);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}