package com.haoyu.family_blog.mapper;

import com.haoyu.family_blog.Model.BlogVisitLog;
import com.haoyu.family_blog.Model.BlogVisitLogExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface BlogVisitLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @SelectProvider(type = BlogVisitLogSqlProvider.class, method = "countByExample")
    int countByExample(BlogVisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @DeleteProvider(type = BlogVisitLogSqlProvider.class, method = "deleteByExample")
    int deleteByExample(BlogVisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @Delete({
            "delete from blog_visit_log",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @Insert({
            "insert into blog_visit_log (userId, blogId, ",
            "visitTime, hide)",
            "values (#{userid,jdbcType=BIGINT}, #{blogid,jdbcType=BIGINT}, ",
            "#{visittime,jdbcType=TIMESTAMP}, #{hide,jdbcType=INTEGER})"
    })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(BlogVisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @InsertProvider(type = BlogVisitLogSqlProvider.class, method = "insertSelective")
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insertSelective(BlogVisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @SelectProvider(type = BlogVisitLogSqlProvider.class, method = "selectByExample")
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
            @Result(column = "userId", property = "userid", jdbcType = JdbcType.BIGINT),
            @Result(column = "blogId", property = "blogid", jdbcType = JdbcType.BIGINT),
            @Result(column = "visitTime", property = "visittime", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "hide", property = "hide", jdbcType = JdbcType.INTEGER)
    })
    List<BlogVisitLog> selectByExample(BlogVisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @Select({
            "select",
            "id, userId, blogId, visitTime, hide",
            "from blog_visit_log",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
            @Result(column = "userId", property = "userid", jdbcType = JdbcType.BIGINT),
            @Result(column = "blogId", property = "blogid", jdbcType = JdbcType.BIGINT),
            @Result(column = "visitTime", property = "visittime", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "hide", property = "hide", jdbcType = JdbcType.INTEGER)
    })
    BlogVisitLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @UpdateProvider(type = BlogVisitLogSqlProvider.class, method = "updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BlogVisitLog record, @Param("example") BlogVisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @UpdateProvider(type = BlogVisitLogSqlProvider.class, method = "updateByExample")
    int updateByExample(@Param("record") BlogVisitLog record, @Param("example") BlogVisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @UpdateProvider(type = BlogVisitLogSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BlogVisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @Update({
            "update blog_visit_log",
            "set userId = #{userid,jdbcType=BIGINT},",
            "blogId = #{blogid,jdbcType=BIGINT},",
            "visitTime = #{visittime,jdbcType=TIMESTAMP},",
            "hide = #{hide,jdbcType=INTEGER}",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(BlogVisitLog record);
}