package com.haoyu.family_blog.mapper;

import com.haoyu.family_blog.Model.BlogVisitLog;
import com.haoyu.family_blog.Model.BlogVisitLogExample;
import com.haoyu.family_blog.Model.BlogVisitLogExample.Criteria;
import com.haoyu.family_blog.Model.BlogVisitLogExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class BlogVisitLogSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String countByExample(BlogVisitLogExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("blog_visit_log");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String deleteByExample(BlogVisitLogExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("blog_visit_log");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String insertSelective(BlogVisitLog record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("blog_visit_log");

        if (record.getUserid() != null) {
            sql.VALUES("userId", "#{userid,jdbcType=BIGINT}");
        }

        if (record.getBlogid() != null) {
            sql.VALUES("blogId", "#{blogid,jdbcType=BIGINT}");
        }

        if (record.getVisittime() != null) {
            sql.VALUES("visitTime", "#{visittime,jdbcType=TIMESTAMP}");
        }

        if (record.getHide() != null) {
            sql.VALUES("hide", "#{hide,jdbcType=INTEGER}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String selectByExample(BlogVisitLogExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("userId");
        sql.SELECT("blogId");
        sql.SELECT("visitTime");
        sql.SELECT("hide");
        sql.FROM("blog_visit_log");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        BlogVisitLog record = (BlogVisitLog) parameter.get("record");
        BlogVisitLogExample example = (BlogVisitLogExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("blog_visit_log");

        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=BIGINT}");
        }

        if (record.getUserid() != null) {
            sql.SET("userId = #{record.userid,jdbcType=BIGINT}");
        }

        if (record.getBlogid() != null) {
            sql.SET("blogId = #{record.blogid,jdbcType=BIGINT}");
        }

        if (record.getVisittime() != null) {
            sql.SET("visitTime = #{record.visittime,jdbcType=TIMESTAMP}");
        }

        if (record.getHide() != null) {
            sql.SET("hide = #{record.hide,jdbcType=INTEGER}");
        }

        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("blog_visit_log");

        sql.SET("id = #{record.id,jdbcType=BIGINT}");
        sql.SET("userId = #{record.userid,jdbcType=BIGINT}");
        sql.SET("blogId = #{record.blogid,jdbcType=BIGINT}");
        sql.SET("visitTime = #{record.visittime,jdbcType=TIMESTAMP}");
        sql.SET("hide = #{record.hide,jdbcType=INTEGER}");

        BlogVisitLogExample example = (BlogVisitLogExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    public String updateByPrimaryKeySelective(BlogVisitLog record) {
        SQL sql = new SQL();
        sql.UPDATE("blog_visit_log");

        if (record.getUserid() != null) {
            sql.SET("userId = #{userid,jdbcType=BIGINT}");
        }

        if (record.getBlogid() != null) {
            sql.SET("blogId = #{blogid,jdbcType=BIGINT}");
        }

        if (record.getVisittime() != null) {
            sql.SET("visitTime = #{visittime,jdbcType=TIMESTAMP}");
        }

        if (record.getHide() != null) {
            sql.SET("hide = #{hide,jdbcType=INTEGER}");
        }

        sql.WHERE("id = #{id,jdbcType=BIGINT}");

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_visit_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    protected void applyWhere(SQL sql, BlogVisitLogExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}