package com.haoyu.family_blog.mapper;

import com.haoyu.family_blog.Model.Images;
import com.haoyu.family_blog.Model.ImagesExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface ImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @SelectProvider(type = ImagesSqlProvider.class, method = "countByExample")
    int countByExample(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @DeleteProvider(type = ImagesSqlProvider.class, method = "deleteByExample")
    int deleteByExample(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @Delete({
            "delete from images",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @Insert({
            "insert into images (uploaded_by, time, ",
            "link, accorded_blog)",
            "values (#{uploadedBy,jdbcType=BIGINT}, #{time,jdbcType=TIMESTAMP}, ",
            "#{link,jdbcType=VARCHAR}, #{accordedBlog,jdbcType=BIGINT})"
    })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @InsertProvider(type = ImagesSqlProvider.class, method = "insertSelective")
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insertSelective(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @SelectProvider(type = ImagesSqlProvider.class, method = "selectByExample")
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
            @Result(column = "uploaded_by", property = "uploadedBy", jdbcType = JdbcType.BIGINT),
            @Result(column = "time", property = "time", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "link", property = "link", jdbcType = JdbcType.VARCHAR),
            @Result(column = "accorded_blog", property = "accordedBlog", jdbcType = JdbcType.BIGINT)
    })
    List<Images> selectByExample(ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @Select({
            "select",
            "id, uploaded_by, time, link, accorded_blog",
            "from images",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
            @Result(column = "uploaded_by", property = "uploadedBy", jdbcType = JdbcType.BIGINT),
            @Result(column = "time", property = "time", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "link", property = "link", jdbcType = JdbcType.VARCHAR),
            @Result(column = "accorded_blog", property = "accordedBlog", jdbcType = JdbcType.BIGINT)
    })
    Images selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @UpdateProvider(type = ImagesSqlProvider.class, method = "updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Images record, @Param("example") ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @UpdateProvider(type = ImagesSqlProvider.class, method = "updateByExample")
    int updateByExample(@Param("record") Images record, @Param("example") ImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @UpdateProvider(type = ImagesSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Images record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @Update({
            "update images",
            "set uploaded_by = #{uploadedBy,jdbcType=BIGINT},",
            "time = #{time,jdbcType=TIMESTAMP},",
            "link = #{link,jdbcType=VARCHAR},",
            "accorded_blog = #{accordedBlog,jdbcType=BIGINT}",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Images record);
}