package com.haoyu.family_blog.mapper;

import com.haoyu.family_blog.Model.UserLoginLog;
import com.haoyu.family_blog.Model.UserLoginLogExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface UserLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @SelectProvider(type = UserLoginLogSqlProvider.class, method = "countByExample")
    int countByExample(UserLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @DeleteProvider(type = UserLoginLogSqlProvider.class, method = "deleteByExample")
    int deleteByExample(UserLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @Delete({
            "delete from user_login_log",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @Insert({
            "insert into user_login_log (user_id, time, ",
            "ip, address, user_agent)",
            "values (#{userId,jdbcType=BIGINT}, #{time,jdbcType=TIMESTAMP}, ",
            "#{ip,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, #{userAgent,jdbcType=VARCHAR})"
    })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(UserLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @InsertProvider(type = UserLoginLogSqlProvider.class, method = "insertSelective")
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insertSelective(UserLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @SelectProvider(type = UserLoginLogSqlProvider.class, method = "selectByExample")
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
            @Result(column = "user_id", property = "userId", jdbcType = JdbcType.BIGINT),
            @Result(column = "time", property = "time", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "ip", property = "ip", jdbcType = JdbcType.VARCHAR),
            @Result(column = "address", property = "address", jdbcType = JdbcType.VARCHAR),
            @Result(column = "user_agent", property = "userAgent", jdbcType = JdbcType.VARCHAR)
    })
    List<UserLoginLog> selectByExample(UserLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @Select({
            "select",
            "id, user_id, time, ip, address, user_agent",
            "from user_login_log",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
            @Result(column = "user_id", property = "userId", jdbcType = JdbcType.BIGINT),
            @Result(column = "time", property = "time", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "ip", property = "ip", jdbcType = JdbcType.VARCHAR),
            @Result(column = "address", property = "address", jdbcType = JdbcType.VARCHAR),
            @Result(column = "user_agent", property = "userAgent", jdbcType = JdbcType.VARCHAR)
    })
    UserLoginLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @UpdateProvider(type = UserLoginLogSqlProvider.class, method = "updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserLoginLog record, @Param("example") UserLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @UpdateProvider(type = UserLoginLogSqlProvider.class, method = "updateByExample")
    int updateByExample(@Param("record") UserLoginLog record, @Param("example") UserLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @UpdateProvider(type = UserLoginLogSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_log
     *
     * @mbggenerated Fri Apr 24 08:57:56 CST 2020
     */
    @Update({
            "update user_login_log",
            "set user_id = #{userId,jdbcType=BIGINT},",
            "time = #{time,jdbcType=TIMESTAMP},",
            "ip = #{ip,jdbcType=VARCHAR},",
            "address = #{address,jdbcType=VARCHAR},",
            "user_agent = #{userAgent,jdbcType=VARCHAR}",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserLoginLog record);
}